#include "pomp_lib.h"

struct ompregdescr omp_rd_22 = {
  "parallelfor", "", 0, "matFact.c", 157, 157, 163, 163
};

#define POMP_DLIST_00022 shared(omp_rd_22)

struct ompregdescr omp_rd_23 = {
  "parallelfor", "", 0, "matFact.c", 165, 165, 184, 184
};

#define POMP_DLIST_00023 shared(omp_rd_23)

struct ompregdescr omp_rd_24 = {
  "parallelfor", "", 0, "matFact.c", 268, 268, 274, 274
};

#define POMP_DLIST_00024 shared(omp_rd_24)

struct ompregdescr omp_rd_25 = {
  "parallelfor", "", 0, "matFact.c", 278, 278, 282, 282
};

#define POMP_DLIST_00025 shared(omp_rd_25)

struct ompregdescr omp_rd_26 = {
  "parallelfor", "", 0, "matFact.c", 286, 286, 292, 292
};

#define POMP_DLIST_00026 shared(omp_rd_26)

struct ompregdescr omp_rd_27 = {
  "parallelfor", "", 0, "matFact.c", 301, 301, 315, 315
};

#define POMP_DLIST_00027 shared(omp_rd_27)

