#include "pomp_lib.h"

struct ompregdescr omp_rd_122 = {
  "parallel", "", 0, "matFact.c", 114, 114, 148, 148
};

#define POMP_DLIST_00122 shared(omp_rd_122,omp_rd_123,omp_rd_124)

struct ompregdescr omp_rd_123 = {
  "for", "", 0, "matFact.c", 116, 116, 130, 130
};

struct ompregdescr omp_rd_124 = {
  "for", "", 0, "matFact.c", 133, 133, 147, 147
};

struct ompregdescr omp_rd_125 = {
  "parallelfor", "", 0, "matFact.c", 154, 154, 162, 162
};

#define POMP_DLIST_00125 shared(omp_rd_125)

struct ompregdescr omp_rd_126 = {
  "parallel", "", 0, "matFact.c", 164, 164, 186, 186
};

#define POMP_DLIST_00126 shared(omp_rd_126,omp_rd_127)

struct ompregdescr omp_rd_127 = {
  "for", "", 0, "matFact.c", 166, 166, 185, 185
};

struct ompregdescr omp_rd_128 = {
  "parallel", "", 0, "matFact.c", 273, 273, 286, 286
};

#define POMP_DLIST_00128 shared(omp_rd_128,omp_rd_129)

struct ompregdescr omp_rd_129 = {
  "for", "", 0, "matFact.c", 275, 275, 285, 285
};

